// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeDrive(arg1, arg2) {
  return window['go']['backend']['App']['AuthorizeDrive'](arg1, arg2);
}

export function CheckCloudExists(arg1) {
  return window['go']['backend']['App']['CheckCloudExists'](arg1);
}

export function CleanLocks(arg1) {
  return window['go']['backend']['App']['CleanLocks'](arg1);
}

export function CreateServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CreateServer'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteServer(arg1, arg2) {
  return window['go']['backend']['App']['DeleteServer'](arg1, arg2);
}

export function FindProcessLockingFile(arg1) {
  return window['go']['backend']['App']['FindProcessLockingFile'](arg1);
}

export function ForceKillPort(arg1) {
  return window['go']['backend']['App']['ForceKillPort'](arg1);
}

export function ForceSyncUp(arg1) {
  return window['go']['backend']['App']['ForceSyncUp'](arg1);
}

export function GetMyServers(arg1) {
  return window['go']['backend']['App']['GetMyServers'](arg1);
}

export function GetPlayerLists(arg1) {
  return window['go']['backend']['App']['GetPlayerLists'](arg1);
}

export function GetServerOptions(arg1) {
  return window['go']['backend']['App']['GetServerOptions'](arg1);
}

export function GetVersions() {
  return window['go']['backend']['App']['GetVersions']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function ImportPlayitConfig(arg1) {
  return window['go']['backend']['App']['ImportPlayitConfig'](arg1);
}

export function InjectConfig(arg1) {
  return window['go']['backend']['App']['InjectConfig'](arg1);
}

export function InstallServer(arg1) {
  return window['go']['backend']['App']['InstallServer'](arg1);
}

export function JoinServer(arg1, arg2) {
  return window['go']['backend']['App']['JoinServer'](arg1, arg2);
}

export function KillMinecraftServer() {
  return window['go']['backend']['App']['KillMinecraftServer']();
}

export function KillProcessesLockingLogs(arg1) {
  return window['go']['backend']['App']['KillProcessesLockingLogs'](arg1);
}

export function KillZombie(arg1) {
  return window['go']['backend']['App']['KillZombie'](arg1);
}

export function LaunchPlayitExternally(arg1) {
  return window['go']['backend']['App']['LaunchPlayitExternally'](arg1);
}

export function Log(arg1) {
  return window['go']['backend']['App']['Log'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['backend']['App']['Login'](arg1, arg2);
}

export function ManagePlayer(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ManagePlayer'](arg1, arg2, arg3, arg4);
}

export function PurgeRemote(arg1) {
  return window['go']['backend']['App']['PurgeRemote'](arg1);
}

export function Register(arg1, arg2) {
  return window['go']['backend']['App']['Register'](arg1, arg2);
}

export function RunMinecraftServer(arg1, arg2) {
  return window['go']['backend']['App']['RunMinecraftServer'](arg1, arg2);
}

export function RunSync(arg1, arg2, arg3) {
  return window['go']['backend']['App']['RunSync'](arg1, arg2, arg3);
}

export function SaveServerOptions(arg1, arg2) {
  return window['go']['backend']['App']['SaveServerOptions'](arg1, arg2);
}

export function SaveWorldSetting(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveWorldSetting'](arg1, arg2, arg3);
}

export function SeedVersions() {
  return window['go']['backend']['App']['SeedVersions']();
}

export function SendConsoleCommand(arg1, arg2) {
  return window['go']['backend']['App']['SendConsoleCommand'](arg1, arg2);
}

export function StartPlayitTunnel(arg1) {
  return window['go']['backend']['App']['StartPlayitTunnel'](arg1);
}

export function StartServer(arg1, arg2) {
  return window['go']['backend']['App']['StartServer'](arg1, arg2);
}

export function StopServer(arg1, arg2) {
  return window['go']['backend']['App']['StopServer'](arg1, arg2);
}

export function StopTunnel() {
  return window['go']['backend']['App']['StopTunnel']();
}

export function UpdateServerProperties(arg1, arg2) {
  return window['go']['backend']['App']['UpdateServerProperties'](arg1, arg2);
}
