// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1, arg2) {
  return window['go']['backend']['App']['CreateServer'](arg1, arg2);
}

export function GetMyServers(arg1) {
  return window['go']['backend']['App']['GetMyServers'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function JoinServer(arg1, arg2) {
  return window['go']['backend']['App']['JoinServer'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['backend']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['backend']['App']['Register'](arg1, arg2);
}

export function RunSync(arg1, arg2, arg3) {
  return window['go']['backend']['App']['RunSync'](arg1, arg2, arg3);
}

export function StartServer(arg1, arg2) {
  return window['go']['backend']['App']['StartServer'](arg1, arg2);
}

export function StopServer(arg1, arg2) {
  return window['go']['backend']['App']['StopServer'](arg1, arg2);
}
