// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AuthorizeDrive(arg1:string,arg2:string):Promise<string>;

export function CheckCloudExists(arg1:string):Promise<boolean>;

export function CheckDependencies():Promise<boolean>;

export function CleanLocks(arg1:string):Promise<void>;

export function CreateServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DeleteServer(arg1:string,arg2:string):Promise<string>;

export function FindProcessLockingFile(arg1:string):Promise<Array<number>>;

export function ForceKillPort(arg1:number):Promise<void>;

export function ForceSyncUp(arg1:string):Promise<string>;

export function GetMyServers(arg1:string):Promise<Array<backend.ServerGroup>>;

export function GetPlayerLists(arg1:string):Promise<backend.PlayerLists>;

export function GetServerOptions(arg1:string):Promise<backend.ServerProps>;

export function GetVersions():Promise<Array<backend.ServerVersion>>;

export function Greet(arg1:string):Promise<string>;

export function ImportPlayitConfig(arg1:string):Promise<string>;

export function InjectConfig(arg1:string):Promise<void>;

export function InstallDependencies():Promise<void>;

export function InstallServer(arg1:string):Promise<string>;

export function JoinServer(arg1:string,arg2:string):Promise<string>;

export function KillMinecraftServer():Promise<void>;

export function KillProcessesLockingLogs(arg1:string):Promise<void>;

export function KillZombie(arg1:string):Promise<void>;

export function LaunchPlayitExternally(arg1:string):Promise<string>;

export function Log(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function ManagePlayer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function PurgeRemote(arg1:string):Promise<void>;

export function Register(arg1:string,arg2:string):Promise<string>;

export function RunMinecraftServer(arg1:string,arg2:number):Promise<void>;

export function RunSync(arg1:backend.SyncDirection,arg2:string,arg3:string):Promise<void>;

export function SaveServerOptions(arg1:string,arg2:backend.ServerProps):Promise<string>;

export function SaveWorldSetting(arg1:string,arg2:string,arg3:any):Promise<string>;

export function SeedVersions():Promise<void>;

export function SendConsoleCommand(arg1:string,arg2:string):Promise<string>;

export function StartPlayitTunnel(arg1:string):Promise<void>;

export function StartServer(arg1:string,arg2:string):Promise<string>;

export function StopServer(arg1:string,arg2:string):Promise<string>;

export function StopTunnel():Promise<void>;

export function UpdateServerProperties(arg1:string,arg2:number):Promise<void>;
