// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateServer(arg1:string,arg2:string):Promise<string>;

export function GetMyServers(arg1:string):Promise<Array<backend.ServerGroup>>;

export function Greet(arg1:string):Promise<string>;

export function JoinServer(arg1:string,arg2:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Register(arg1:string,arg2:string):Promise<string>;

export function StartServer(arg1:string,arg2:string):Promise<string>;

export function StopServer(arg1:string,arg2:string):Promise<string>;
